name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pipenv'
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv 
        pipenv install
    - name: Update README
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
      run: |-
        pipenv run python generate_stats_svg.py generate-live
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add strava_stats.svg && git commit -m "Updated README")
        git push
